/* jshint browser: true */
var arrplaces = [
	'Lighthouse',
	'Living Room',
	'Museum',
	'Zoo',
	'Swimming Pool',
	'Office',
	'Bank',
	'Attic',
	'Library',
	'GolfCourse',
	'Garden',
	'School',
	'House',
	'Bed Room',
	'Kitchen',
	'Store',
	'Mall',
	'Space',
	'Alien Planet',
	'Space Shuttle',
	'Car Interior',
	'Used Car Lot',
	'The Jungle',
	'The City',
	'The Country',
	'The moon',
	'The North Pole',
	'Offce',
	'Kitchen',
	'Bar',
	'Dining Room',
	'Igloo',
	'Aeroplane',
	'Airport',
	'Iceberg',
	'Mountain',
	'Forest',
	'Movie Theater',
	'Film Set',
	'Operating Room',
	'Beauty Parlor',
	'Shower',
	'Hardware Store',
	'Merry Go Round',
	'Barber/Beauty School',
	'Swimming Pool',
	'Baseball Field',
	'Basketball Court',
	'Tennis Court',
	'Skating/Hockey Rink',
	'The Suburbs',
	'Self-service elevator',
	'Card Game', 
	'Drive-in movie', 
	'Housing development', 
	'Laundromat',
	'Sewer', 
	'Penthouse',  
	'Police station', 
	'Motorcycle', 
	'Dog house', 
	'Menagerie', 
	'Steam bath',  
	'Garage', 
	'Outdoor cafe',  
	'Attic', 
	'College', 
	'Skyscraper', 
	'Covered wagon', 
	'Supermarket', 
	'Airport', 
	'Roller coaster', 
	'Dog kennel', 
	'Tunnel of Love',
	'Aquarium', 
	'Archery range', 
	'Shooting range',
	'Ballroom', 
	'Drive-thru bank/resturant',
	'Window display', 
	'Drawbridge', 
	'Cage', 
	'Bull ring',
	'Daycare',
	'Hideout',
	'Camp Ground',
	'Coffee Shop',
	'Principals Office',
	'Exam Room',
	'Psychatrists chair',
	'Finished Basement',
	'Man Cave',
	'Bear Cave',
	'Haunted House',
	'Den/Study',
	'Art Studio',
	'Dance Studio',
	"Gym",
	'Strip Mall',
	'Ticker Tape Parade'
];


function places() {
	"use strict";
	var randomNumber = Math.floor(Math.random() * (arrplaces.length));
	document.getElementById('places').innerHTML = arrplaces[randomNumber];
}
